name: isazi_test_venv
channels:
  - conda-forge
  - anaconda
dependencies:
  - conda-forge::python=3.8.15
  - conda-forge::numpy=1.24.2
  - conda-forge::matplotlib=3.7.1
  - conda-forge::pip
  - conda-forge::jupyterlab=2.2.4
  - folium=0.14.0
  - pip:
      - ortools==9.6.2534
      - protobuf==4.21.12
      - pyproj==3.1.0
      - geopandas==0.9.0
variables:
  TEST_VAR: this_is_a_test_variable
